const map = new Map()
console.log(map.size)
map.set('Jonh Snow', 'Casa Targaryen')
map.set('Daenerys', 'Casa Targaryen')
map.set('Tyrion', 'Casa Lannister')
map.set('Cersei', 'Casa Lannister')
map.set('Margaery', 'Casa Tyrell')
map.set('Sansa', 'Casa Stark')
map.set('Arya', 'Casa Stark')
map.set('Robert', 'Casa Baratheon')
map.set('Oberyn', 'Casa Martell')
map.set('Theon', 'Casa Greyjoy')
console.log(map.size)
console.log(map.keys())
console.log(map.values())
console.log(map.has('Daenerys'))
console.log(map.has('Jamie'))
map.delete('Robert')
map.delete('Theon')
map.delete('Oberyn')
map.delete('Tyrion')
map.delete('Jonh Snow')
console.log(map.keys())
console.log(map.values())
console.log(map.get('Sansa'))
console.log(map.get('Cersei'))
console.log(map.get('Daenerys'))
console.log(map.get('Arya'))
console.log(map.get('Margaery'))
map.clear()
console.log(map.size)
console.log(map.keys())
console.log(map.values())

